# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: zookeeper.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fzookeeper.proto\x12\tzookeeper\"e\n\x08Proposal\x12\r\n\x05\x65poch\x18\x01 \x01(\x05\x12\x0b\n\x03seq\x18\x02 \x01(\x05\x12\x1d\n\x02op\x18\x03 \x01(\x0e\x32\x11.zookeeper.OpType\x12\r\n\x05value\x18\x04 \x01(\t\x12\x0f\n\x07\x66rom_id\x18\x05 \x01(\t\"D\n\x03\x41\x63k\x12\r\n\x05\x65poch\x18\x01 \x01(\x05\x12\x0b\n\x03seq\x18\x02 \x01(\x05\x12\x0f\n\x07\x66rom_id\x18\x03 \x01(\t\x12\x10\n\x08\x61\x63\x63\x65pted\x18\x04 \x01(\x08\"3\n\x06\x43ommit\x12\r\n\x05\x65poch\x18\x01 \x01(\x05\x12\x0b\n\x03seq\x18\x02 \x01(\x05\x12\r\n\x05value\x18\x03 \x01(\t\"1\n\tHeartbeat\x12\x11\n\tleader_id\x18\x01 \x01(\t\x12\x11\n\ttimestamp\x18\x02 \x01(\x03\"<\n\x08\x45lection\x12\x14\n\x0c\x63\x61ndidate_id\x18\x01 \x01(\t\x12\r\n\x05\x65poch\x18\x02 \x01(\x05\x12\x0b\n\x03seq\x18\x03 \x01(\x05\"9\n\x04Vote\x12\x10\n\x08voter_id\x18\x01 \x01(\t\x12\x10\n\x08vote_for\x18\x02 \x01(\t\x12\r\n\x05\x65poch\x18\x03 \x01(\x05\"\x07\n\x05\x45mpty\"=\n\rClientRequest\x12\x1d\n\x02op\x18\x01 \x01(\x0e\x32\x11.zookeeper.OpType\x12\r\n\x05value\x18\x02 \x01(\t\"J\n\x0e\x43lientResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x16\n\x0e\x63urrent_target\x18\x03 \x01(\t*]\n\x06OpType\x12\x0b\n\x07UNKNOWN\x10\x00\x12\t\n\x05WRITE\x10\x01\x12\t\n\x05GUESS\x10\x02\x12\r\n\tHEARTBEAT\x10\x03\x12\x0c\n\x08\x45LECTION\x10\x04\x12\x07\n\x03\x41\x43K\x10\x05\x12\n\n\x06\x43OMMIT\x10\x06\x32\x95\x02\n\x0bNodeService\x12\x33\n\x0cSendProposal\x12\x13.zookeeper.Proposal\x1a\x0e.zookeeper.Ack\x12\x31\n\nSendCommit\x12\x11.zookeeper.Commit\x1a\x10.zookeeper.Empty\x12\x37\n\rSendHeartbeat\x12\x14.zookeeper.Heartbeat\x1a\x10.zookeeper.Empty\x12\x35\n\rStartElection\x12\x13.zookeeper.Election\x1a\x0f.zookeeper.Vote\x12.\n\x08KillSelf\x12\x10.zookeeper.Empty\x1a\x10.zookeeper.Empty2U\n\rClientService\x12\x44\n\rSubmitRequest\x12\x18.zookeeper.ClientRequest\x1a\x19.zookeeper.ClientResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'zookeeper_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_OPTYPE']._serialized_start=576
  _globals['_OPTYPE']._serialized_end=669
  _globals['_PROPOSAL']._serialized_start=30
  _globals['_PROPOSAL']._serialized_end=131
  _globals['_ACK']._serialized_start=133
  _globals['_ACK']._serialized_end=201
  _globals['_COMMIT']._serialized_start=203
  _globals['_COMMIT']._serialized_end=254
  _globals['_HEARTBEAT']._serialized_start=256
  _globals['_HEARTBEAT']._serialized_end=305
  _globals['_ELECTION']._serialized_start=307
  _globals['_ELECTION']._serialized_end=367
  _globals['_VOTE']._serialized_start=369
  _globals['_VOTE']._serialized_end=426
  _globals['_EMPTY']._serialized_start=428
  _globals['_EMPTY']._serialized_end=435
  _globals['_CLIENTREQUEST']._serialized_start=437
  _globals['_CLIENTREQUEST']._serialized_end=498
  _globals['_CLIENTRESPONSE']._serialized_start=500
  _globals['_CLIENTRESPONSE']._serialized_end=574
  _globals['_NODESERVICE']._serialized_start=672
  _globals['_NODESERVICE']._serialized_end=949
  _globals['_CLIENTSERVICE']._serialized_start=951
  _globals['_CLIENTSERVICE']._serialized_end=1036
# @@protoc_insertion_point(module_scope)
