# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import zookeeper_pb2 as zookeeper__pb2

GRPC_GENERATED_VERSION = '1.64.0'
GRPC_VERSION = grpc.__version__
EXPECTED_ERROR_RELEASE = '1.65.0'
SCHEDULED_RELEASE_DATE = 'June 25, 2024'
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    warnings.warn(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in zookeeper_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
        + f' This warning will become an error in {EXPECTED_ERROR_RELEASE},'
        + f' scheduled for release on {SCHEDULED_RELEASE_DATE}.',
        RuntimeWarning
    )


class NodeServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SendProposal = channel.unary_unary(
                '/zookeeper.NodeService/SendProposal',
                request_serializer=zookeeper__pb2.Proposal.SerializeToString,
                response_deserializer=zookeeper__pb2.Ack.FromString,
                _registered_method=True)
        self.SendCommit = channel.unary_unary(
                '/zookeeper.NodeService/SendCommit',
                request_serializer=zookeeper__pb2.Commit.SerializeToString,
                response_deserializer=zookeeper__pb2.Empty.FromString,
                _registered_method=True)
        self.SendHeartbeat = channel.unary_unary(
                '/zookeeper.NodeService/SendHeartbeat',
                request_serializer=zookeeper__pb2.Heartbeat.SerializeToString,
                response_deserializer=zookeeper__pb2.Empty.FromString,
                _registered_method=True)
        self.StartElection = channel.unary_unary(
                '/zookeeper.NodeService/StartElection',
                request_serializer=zookeeper__pb2.Election.SerializeToString,
                response_deserializer=zookeeper__pb2.Vote.FromString,
                _registered_method=True)
        self.KillSelf = channel.unary_unary(
                '/zookeeper.NodeService/KillSelf',
                request_serializer=zookeeper__pb2.Empty.SerializeToString,
                response_deserializer=zookeeper__pb2.Empty.FromString,
                _registered_method=True)


class NodeServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SendProposal(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendCommit(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendHeartbeat(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StartElection(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def KillSelf(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_NodeServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SendProposal': grpc.unary_unary_rpc_method_handler(
                    servicer.SendProposal,
                    request_deserializer=zookeeper__pb2.Proposal.FromString,
                    response_serializer=zookeeper__pb2.Ack.SerializeToString,
            ),
            'SendCommit': grpc.unary_unary_rpc_method_handler(
                    servicer.SendCommit,
                    request_deserializer=zookeeper__pb2.Commit.FromString,
                    response_serializer=zookeeper__pb2.Empty.SerializeToString,
            ),
            'SendHeartbeat': grpc.unary_unary_rpc_method_handler(
                    servicer.SendHeartbeat,
                    request_deserializer=zookeeper__pb2.Heartbeat.FromString,
                    response_serializer=zookeeper__pb2.Empty.SerializeToString,
            ),
            'StartElection': grpc.unary_unary_rpc_method_handler(
                    servicer.StartElection,
                    request_deserializer=zookeeper__pb2.Election.FromString,
                    response_serializer=zookeeper__pb2.Vote.SerializeToString,
            ),
            'KillSelf': grpc.unary_unary_rpc_method_handler(
                    servicer.KillSelf,
                    request_deserializer=zookeeper__pb2.Empty.FromString,
                    response_serializer=zookeeper__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'zookeeper.NodeService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('zookeeper.NodeService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class NodeService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SendProposal(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/zookeeper.NodeService/SendProposal',
            zookeeper__pb2.Proposal.SerializeToString,
            zookeeper__pb2.Ack.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendCommit(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/zookeeper.NodeService/SendCommit',
            zookeeper__pb2.Commit.SerializeToString,
            zookeeper__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendHeartbeat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/zookeeper.NodeService/SendHeartbeat',
            zookeeper__pb2.Heartbeat.SerializeToString,
            zookeeper__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StartElection(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/zookeeper.NodeService/StartElection',
            zookeeper__pb2.Election.SerializeToString,
            zookeeper__pb2.Vote.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def KillSelf(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/zookeeper.NodeService/KillSelf',
            zookeeper__pb2.Empty.SerializeToString,
            zookeeper__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class ClientServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SubmitRequest = channel.unary_unary(
                '/zookeeper.ClientService/SubmitRequest',
                request_serializer=zookeeper__pb2.ClientRequest.SerializeToString,
                response_deserializer=zookeeper__pb2.ClientResponse.FromString,
                _registered_method=True)


class ClientServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SubmitRequest(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ClientServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SubmitRequest': grpc.unary_unary_rpc_method_handler(
                    servicer.SubmitRequest,
                    request_deserializer=zookeeper__pb2.ClientRequest.FromString,
                    response_serializer=zookeeper__pb2.ClientResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'zookeeper.ClientService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('zookeeper.ClientService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ClientService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SubmitRequest(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/zookeeper.ClientService/SubmitRequest',
            zookeeper__pb2.ClientRequest.SerializeToString,
            zookeeper__pb2.ClientResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
