#!/usr/bin/env python3

"""
Script for terminating the current leader node.

This module is invoked via ``python -m scripts.kill_leader`` and issues a
``KillSelf`` RPC to the leader listed in ``config/nodes.txt``. A gRPC error
on call completion indicates successful termination, while a normal return
indicates failure.
"""


import grpc
from core.config import config_path
from zk import zookeeper_pb2, zookeeper_pb2_grpc


def find_leader():
    """
    Locate the current leader from ``config/nodes.txt``.

    Note:
        The function parses the configuration file generated by the running
        leader. A valid leader entry has the format:
        ``leader <node_id> <port>``.

    :return:
        A dictionary containing ``{"id": str, "port": int}`` if a leader
        entry exists; otherwise ``None``.
    """

    if not config_path.exists():
        print("❌ config/nodes.txt not found.")
        return None

    try:
        lines = [
            l.strip()
            for l in config_path.read_text().splitlines()
            if l.strip() and not l.startswith("#")
        ]
        for l in lines:
            parts = l.split()
            if len(parts) == 3 and parts[0] == "leader":
                return {"id": parts[1], "port": int(parts[2])}
        print("⚠️  No leader entry found in config.")
        return None
    except Exception as e:
        print(f"❌ Failed to read config: {e}")
        return None


def kill_leader():
    """
    Send a termination request to the current leader.

    Note:
        This function issues a ``KillSelf`` RPC to the leader. Because the
        leader process exits immediately, a gRPC error such as socket closure
        indicates success. A normal RPC return indicates failure to terminate.

    :return: None
    """

    leader = find_leader()
    if not leader:
        return

    port = leader["port"]
    node_id = leader["id"]
    print(f"💀 Attempting to kill leader {node_id} (port {port})...")

    try:
        with grpc.insecure_channel(f"localhost:{port}") as channel:
            stub = zookeeper_pb2_grpc.NodeServiceStub(channel)
            stub.KillSelf(zookeeper_pb2.Empty())

        print(f"⚠️  Kill RPC returned without closing — leader may not have exited.")
    except grpc.RpcError as e:
        if "Socket closed" in str(e) or e.code() == grpc.StatusCode.UNAVAILABLE:
            print(f"✅ Leader {node_id} terminated successfully.")
        else:
            print(f"❌ Unexpected RPC error: {e}")
    except Exception as e:
        print(f"❌ Unexpected error: {e}")


if __name__ == "__main__":
    kill_leader()
